# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
