# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlr', '0002_auto_20180323_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
