# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawlr', '0005_auto_20180327_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='route',
            name='liked_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
